#+TITLE: ericst's Dotfiles
#+AUTHOR: Eric Seuret
#+EMAIL: eric@ericst.ch

* Introduction
Those are my dotfiles. They are supplied in the form of literate Emacs
org-mode. The different configuration are therefore easy to follow,
update and kept in a documented way.

Each file is then tangled directly in the correct files.

* Source
I keep one general file per tool. This file describe then the intended
configuration and can directly be tangled as the configuration if need
be.

You will find those files in the *src* sub-directory.

- [[file:src/Emacs.org][Emacs.org]] :: My Emacs configuration.
- [[file:src/Bash.org][Bash.org]] :: My Bash configuration. Also includes readline.
- [[file:src/Git.org][Git.org]] :: My Git configuration.

* Generation of README                                             :noexport:
The following code when executed with ~C-c C-c~ will export this file
as a nice README for consumption on the terminal, or display on git
websites.

#+begin_src emacs-lisp :tangle no :results silent
  (setq-local org-export-show-temporary-export-buffer 'nil)
  (org-ascii-export-as-ascii 'nil 'nil 'nil 'nil '(:ascii-charset utf-8))
  (set-buffer "*Org ASCII Export*")
  (write-file "README")
  (kill-buffer "README")
#+end_src

