@startuml

[*] -> TODO
TODO -> NEXT
NEXT -> DONE
TODO -> DONE
DONE -> [*] 

TODO --> WAITING
NEXT --> WAITING
WAITING -up-> NEXT
WAITING -up-> DONE

TODO --> HOLD
NEXT --> HOLD
WAITING -> HOLD
HOLD -up->  DONE
HOLD -up-> NEXT
HOLD -up-> WAITING

TODO --> CANCELLED
NEXT --> CANCELLED
WAITING --> CANCELLED
HOLD --> CANCELLED
CANCELLED -up-> [*]

TODO -up-> DELEGATED
NEXT -up-> DELEGATED
WAITING -up-> DELEGATED
HOLD -up-> DELEGATED

DELEGATED --> CANCELLED
DELEGATED --> DONE


@enduml