link 'init.lua', '~/.config/nvim/init.lua'
link 'lua', '~/.config/nvim/lua' 
link 'ftplugin', '~/.config/nvim/ftplugin'
link 'README.md', '~/.config/nvim/README.md'
link 'ctags', '~/.config/ctags'
link 'nvim.desktop', '~/.local/share/applications/nvim.desktop'
