[[links]]
source = "init.lua"
target = "~/.config/nvim/init.lua"

[[links]]
source = "lua"
target = "~/.config/nvim/lua"

[[links]]
source = "ftplugin"
target = "~/.config/nvim/ftplugin"

[[links]]
source = "README.md"
target = "~/.config/nvim/README.md"

[[links]]
source = "ctags"
target = "~/.config/ctags"

[[links]]
source = "nvim.desktop"
target = "~/.local/share/applications/nvim.desktop"
