[[links]]
source = "keybindings.json"
target = "~/.pi/agent/keybindings.json"

[[links]]
source = "prompts"
target = "~/.pi/agent/prompts"

[[links]]
source = "APPEND_SYSTEM.md"
target = "~/.pi/agent/APPEND_SYSTEM.md"

[[links]]
source = "pi-tmux"
target = "~/.bashrc.d/pi-tmux"

[[links]]
source = "models.json"
target = "~/.pi/agent/models.json"

[[links]]
source = "extensions"
target = "~/.pi/agent/extensions"
