[[links]]
source = "bashrc"
target = "~/.bashrc"

[[links]]
source = "bashrc.d"
target = "~/.bashrc.d"
recursive = true

[[links]]
source = "inputrc"
target = "~/.inputrc"

[[links]]
source = "dotfiles-git-check"
target = "~/.local/bin/dotfiles-git-check"

